### PR TITLE
Update a few project dependencies

### PR DESCRIPTION
**Pull request by Jacalz**
- The update of `klauspost/compress` brings in a bunch of smaller improvements to the performance and compression-ratio. It does raise the minimum Go version to Go 1.17 which has the benefit of now enabling lazy module module graph pruning and lazy module loading (basically less of the unused deps need to be downloaded).

- The update of `spf13/cobra` means that it uses `gopkg.in/yaml.v3` instead of `gopkg.in/yaml.v2`, in turn fixing a security issue. This should avoid downstream projects using this project to get dependabot alerts from GitHub.

- The update of `golang.org/x/crypto` fixes a security issue (although not one relevant to this project). However, the update here avoids downstream projects using this project to get dependabot alerts from GitHub.

### CODE REVIEW

**Comment by Jacalz** [comment]
The error does not seem to be the fault of this PR?

**Comment by Jacalz** [comment]
With Go 1.20 having been released today, I think updating to Go 1.17 as the lowest supported compiler version seems sensible.

**Comment by Jacalz** [comment]
Managed to get the tests passing again. Seems like setup-go/v3 was broken.

**Comment by psanford** [comment]
I'm not particularly interested in updating packages simply for the sake of updating them without a concrete benefit. 

Downstream packages that don't like the false positive security scanner alerts can set a newer version of those packages in their go.mod.

**Comment by Jacalz** [comment]
I provided an explanation for every package update. There is no update for the sake of updating here...

**Pull request closed without merging**
