### PR TITLE
Fix send dir on Windows

### PR DESCRIPTION
**Pull request by rixtox**

### CODE REVIEW

**Comment by psanford** [comment]
Thanks for this pr, the change looks good.

I merged a couple of PRs ahead of yours and now there's a minor conflict. Would you mind rebasing this PR onto master?

I also enabled Windows in the github actions so we can get better os test coverage. Would you mind updating the test case to demonstrate the problem? I think it would be as simple as updating the existing `TestWormholeDirectoryTransportSendRecvDirect` to change the two directory entry paths to use `filepath.Join`:
```
"skyjacking/personalize.txt" => filepath.Join("skyjacking", "personalize.txt")
"skyjacking/bodice-Maytag.txt" => filepath.Join("skyjacking", "bodice-Maytag.txt")
```

**Comment by rixtox** [comment]
Rebased, and test updated

**Comment by psanford** [comment]
The commit Author field doesn't seem to be associated with your github account. Can fix that also?

**Comment by rixtox** [comment]
> The commit Author field doesn't seem to be associated with your github account. Can fix that also?

fixed

**Comment by psanford** [comment]
Merged. Thanks again!

**Pull request closed without merging**
