### PR TITLE
cmd: optimize how text receives are printed

### PR DESCRIPTION
**Pull request by Jacalz**
Now that we know the length of the text, we can use ReadFull() with a pre-allocated buffer instead.
ReadAll always allocates 512 bytes minimum and will append as it goes. We now just allocate just as much as needed and do so once only.

I did this for Rymdport as well and figured that it wouldn't hurt being a good open source citizen and improve it here also :)

### CODE REVIEW

**Comment by Jacalz** [comment]
```
BenchmarkReadAll-8               	 7253271	       156.3 ns/op	     544 B/op	       2 allocs/op
BenchmarkReadFull-8              	12244660	        93.98 ns/op	     160 B/op	       2 allocs/op
```

**Comment by psanford** [comment]
Maybe we should just change this to:
```
_, err = io.Copy(os.Stdout, msg)
```

**Comment by Jacalz** [comment]
That seems like a wonderful idea. I hasn’t thought about that at all. Will get this updated tomorrow.

**Comment by Jacalz** [comment]
I should probably have said something sooner, but this should be ready for a re-review.

**Comment by Jacalz** [comment]
I'm just going through and trying to clean up my list of open PRs. Any chance to get this re-reviewed?

**Pull request closed without merging**
