### PR TITLE
wormhole: Don't call reflect twice on message

### PR DESCRIPTION
**Pull request by Jacalz**
Cleans up some code that was doing double reflect calls when only one was necessary,

### CODE REVIEW

**Comment by psanford** [comment]
The go specification does not require an interface implementation to be a pointer type, as long as the method receiver is not a pointer:

```
package main

import (
	"fmt"
)

type concreteFoo struct {
}

func (c concreteFoo) String() string {
	return "concreteFoo"
}

type stringer interface {
	String() string
}

func takesAStringer(s stringer) {
	fmt.Println(s.String())
}

func main() {
	f := concreteFoo{}
	takesAStringer(f)
}
```

**Comment by Jacalz** [comment]
But the methods for the collectable types used within the project are all pointer receivers.
image

**Comment by psanford** [comment]
I would take this change If you wrote a static analysis test that showed that every implementation of this interface used pointer types.

**Comment by Jacalz** [comment]
I've pushed a commit to at least not get the value twice from `msg` using reflect. It should be better than nothing in the meantime.

**Comment by Jacalz** [comment]
I might actually have a better fix for this. Will see what I can do.

**Comment by Jacalz** [comment]
I have opened https://github.com/psanford/wormhole-william/pull/95 with a different approach that checks the struct pointer in a different way without using the `reflect` package at all. If that PR is rejected, this is still a nice improvement over the previous code.

**Comment by Jacalz** [comment]
Done

**Comment by Jacalz** [comment]
Ping @psanford

**Pull request closed without merging**
