### PR TITLE
A few smaller code cleanups

### PR DESCRIPTION
**Pull request by Jacalz**
This PR incorporates a couple code cleanups, with some being more important than others. Below is a summary of what has been done:
- The sendOptions were moved out to a separate file for readability.
- Replaced an unnecessary `io.TeeReader` and `countWriter` with the bytes written by `io.Copy` (should be marginally faster than before).
- Fixed the same `prefixPath` being recalculated on each directory iteration (should also result in a small performance improvement).
- Move `variable = variable + number` to `variable += number`.

### CODE REVIEW

**Comment by Jacalz** [comment]
I just need to do a little optimization and removal of duplicated code. Should be able to move the seeking into the sendFileDirectory() function and only try to seek if we actually have provided a progressbar option. After that, I shall open this up for review :slightly_smiling_face:

**Comment by Jacalz** [comment]
I just need to do a little optimization and removal of duplicated code. Should be able to move the seeking into the sendFileDirectory() function and only try to seek if we actually have provided a progressbar option. After that, I shall open this up for review :slightly_smiling_face:

**Comment by psanford** [comment]
The filesize is required as part of the protocol. It is sent in the offer and used by the receiver. I would not expect this to be compatible with any existing wormhole clients.

**Comment by Jacalz** [comment]
Alright then. Will change this PR to only include the code cleanups then.

**Comment by Jacalz** [comment]
Removed the `io.Reader` changes. Just some nice code cleanups now :slightly_smiling_face:

**Comment by psanford** [comment]
Lets not move the sendoptions out of send.go. Otherwise this looks good.

**Comment by Jacalz** [comment]
Sure thing. Should be ready for a re-review now :slightly_smiling_face:

**Comment by Jacalz** [comment]
Ping @psanford. Any chance that you can re-review this?

**Comment by psanford** [comment]
Can you rebase and squash your commits?

**Comment by Jacalz** [comment]
> Can you rebase and squash your commits?

Sure. I can get that done tomorrow. There does not seem to be any conflicts, so you should just be able to squash and merge through GitHub though, if you want to.

**Comment by Jacalz** [comment]
This is now rebased and squashed.

**Pull request closed without merging**
